// Code generated by d:\Desktop\Gamedev\rohin\bin\shader_tool.exe
#include "./shaders_generated.h"

void shader_BRDF_Integrate::InitShaderLocs() {
    outputs.num_outputs = 0;

}
void shader_HDRI_to_cubemap::InitShaderLocs() {
    outputs.num_outputs = 1;
    outputs.FragColor = 0;

    r_Projection.Location = 1;
    r_View.Location = 2;
    u_hdri.Location = 3;
    u_hdri.SamplerID = 0;
}
void shader_IBL_Prefilter::InitShaderLocs() {
    outputs.num_outputs = 1;
    outputs.FragColor = 0;

    r_Projection.Location = 1;
    r_View.Location = 2;
    u_env_cubemap.Location = 3;
    u_env_cubemap.SamplerID = 0;
    r_roughness.Location = 4;
}
void shader_Irradiance_Convolve::InitShaderLocs() {
    outputs.num_outputs = 1;
    outputs.FragColor = 0;

    r_Projection.Location = 1;
    r_View.Location = 2;
    u_env_cubemap.Location = 3;
    u_env_cubemap.SamplerID = 0;
}
void shader_Lighting::InitShaderLocs() {
    outputs.num_outputs = 2;
    outputs.out_Diffuse = 0;
    outputs.out_Specular = 1;

    r_Projection.Location = 1;
    for (unsigned int n = 0; n < 32; n++) {
        r_pointLights[n].Position.Location = 2+(n*6);
        r_pointLights[n].Direction.Location = 3+(n*6);
        r_pointLights[n].Color.Location = 4+(n*6);
        r_pointLights[n].Strength.Location = 5+(n*6);
        r_pointLights[n].Inner.Location = 6+(n*6);
        r_pointLights[n].Outer.Location = 7+(n*6);
    }
    for (unsigned int n = 0; n < 32; n++) {
        r_spotLights[n].Position.Location = 194+(n*6);
        r_spotLights[n].Direction.Location = 195+(n*6);
        r_spotLights[n].Color.Location = 196+(n*6);
        r_spotLights[n].Strength.Location = 197+(n*6);
        r_spotLights[n].Inner.Location = 198+(n*6);
        r_spotLights[n].Outer.Location = 199+(n*6);
    }
    r_sun.Position.Location = 386;
    r_sun.Direction.Location = 387;
    r_sun.Color.Location = 388;
    r_sun.Strength.Location = 389;
    r_sun.Inner.Location = 390;
    r_sun.Outer.Location = 391;
    r_View.Location = 392;
    u_albedo.Location = 393;
    u_albedo.SamplerID = 0;
    u_normal.Location = 394;
    u_normal.SamplerID = 1;
    u_depth.Location = 395;
    u_depth.SamplerID = 2;
    u_amr.Location = 396;
    u_amr.SamplerID = 3;
    u_irradiance.Location = 397;
    u_irradiance.SamplerID = 4;
    u_prefilter.Location = 398;
    u_prefilter.SamplerID = 5;
      u_brdf_LUT.Location = 399;
      u_brdf_LUT.SamplerID = 6;
          u_env_map_contribution.Location = 400;
}
void shader_Line::InitShaderLocs() {
    outputs.num_outputs = 1;
    outputs.FragColor = 0;

    r_VP.Location = 1;
    r_Transform.Location = 2;
    r_CamPos.Location = 3;
    r_LineColor.Location = 4;
    r_LineFadeStart.Location = 5;
    r_LineFadeEnd.Location = 6;
    r_LineFadeMaximum.Location = 7;
    r_LineFadeMinimum.Location = 8;
}
void shader_Line2D::InitShaderLocs() {
    outputs.num_outputs = 0;

    for (unsigned int n = 0; n < 2; n++) {
        r_verts[n].Location = 1+n;
    }
    r_orthoProjection.Location = 3;
    r_Color.Location = 4;
}
void shader_Line3D::InitShaderLocs() {
    outputs.num_outputs = 0;

    for (unsigned int n = 0; n < 2; n++) {
        r_verts[n].Location = 1+n;
    }
    r_View.Location = 3;
    r_Projection.Location = 4;
    r_Color.Location = 5;
}
void shader_Mix::InitShaderLocs() {
    outputs.num_outputs = 0;

    r_tex1.Location = 1;
    r_tex1.SamplerID = 0;
    r_tex2.Location = 2;
    r_tex2.SamplerID = 1;
    r_mixValue.Location = 3;
}
void shader_Normals::InitShaderLocs() {
    outputs.num_outputs = 1;
    outputs.FragColor = 0;

    r_Transform.Location = 1;
    r_VP.Location = 2;
}
void shader_PBR_static::InitShaderLocs() {
    outputs.num_outputs = 1;
    outputs.FragColor = 0;

    r_VP.Location = 1;
    r_Transform.Location = 2;
    for (unsigned int n = 0; n < 32; n++) {
        r_pointLights[n].Position.Location = 3+(n*6);
        r_pointLights[n].Direction.Location = 4+(n*6);
        r_pointLights[n].Color.Location = 5+(n*6);
        r_pointLights[n].Strength.Location = 6+(n*6);
        r_pointLights[n].Inner.Location = 7+(n*6);
        r_pointLights[n].Outer.Location = 8+(n*6);
    }
    for (unsigned int n = 0; n < 32; n++) {
        r_spotLights[n].Position.Location = 195+(n*6);
        r_spotLights[n].Direction.Location = 196+(n*6);
        r_spotLights[n].Color.Location = 197+(n*6);
        r_spotLights[n].Strength.Location = 198+(n*6);
        r_spotLights[n].Inner.Location = 199+(n*6);
        r_spotLights[n].Outer.Location = 200+(n*6);
    }
    r_sun.Position.Location = 387;
    r_sun.Direction.Location = 388;
    r_sun.Color.Location = 389;
    r_sun.Strength.Location = 390;
    r_sun.Inner.Location = 391;
    r_sun.Outer.Location = 392;
    r_CamPos.Location = 393;
    u_AlbedoTexture.Location = 394;
    u_AlbedoTexture.SamplerID = 0;
    u_NormalTexture.Location = 395;
    u_NormalTexture.SamplerID = 1;
    u_MetalnessTexture.Location = 396;
    u_MetalnessTexture.SamplerID = 2;
    u_RoughnessTexture.Location = 397;
    u_RoughnessTexture.SamplerID = 3;
    u_AlbedoColor.Location = 398;
    u_Metalness.Location = 399;
    u_Roughness.Location = 400;
    r_AlbedoTexToggle.Location = 401;
    r_NormalTexToggle.Location = 402;
    r_MetalnessTexToggle.Location = 403;
    r_RoughnessTexToggle.Location = 404;
}
void shader_PrePass::InitShaderLocs() {
    outputs.num_outputs = 5;
    outputs.out_Albedo = 0;
    outputs.out_Normal = 1;
    outputs.out_AMR = 2;
    outputs.out_Emissive = 3;
    outputs.out_Depth = 4;

    r_Transform.Location = 1;
    r_View.Location = 2;
    r_Projection.Location = 3;
    u_AlbedoTexture.Location = 4;
    u_AlbedoTexture.SamplerID = 0;
    u_NormalTexture.Location = 5;
    u_NormalTexture.SamplerID = 1;
    u_MetalnessTexture.Location = 6;
    u_MetalnessTexture.SamplerID = 2;
    u_RoughnessTexture.Location = 7;
    u_RoughnessTexture.SamplerID = 3;
    u_AmbientTexture.Location = 8;
    u_AmbientTexture.SamplerID = 4;
    u_EmissiveTexture.Location = 9;
    u_EmissiveTexture.SamplerID = 5;
    u_AlbedoColor.Location = 10;
    u_Metalness.Location = 11;
    u_Roughness.Location = 12;
    u_TextureScale.Location = 13;
    u_EmissiveColor.Location = 14;
    r_AlbedoTexToggle.Location = 15;
    r_NormalTexToggle.Location = 16;
    r_MetalnessTexToggle.Location = 17;
    r_RoughnessTexToggle.Location = 18;
    r_AmbientTexToggle.Location = 19;
    r_EmissiveTexToggle.Location = 20;
    r_gammaCorrect.Location = 21;
}
void shader_PrePass_Anim::InitShaderLocs() {
    outputs.num_outputs = 5;
    outputs.out_Albedo = 0;
    outputs.out_Normal = 1;
    outputs.out_AMR = 2;
    outputs.out_Emissive = 3;
    outputs.out_Depth = 4;

    for (unsigned int n = 0; n < 128; n++) {
        r_Bones[n].Location = 1+n;
    }
    r_UseSkin.Location = 129;
    r_Transform.Location = 130;
    r_View.Location = 131;
    r_Projection.Location = 132;
    u_AlbedoTexture.Location = 133;
    u_AlbedoTexture.SamplerID = 0;
    u_NormalTexture.Location = 134;
    u_NormalTexture.SamplerID = 1;
    u_MetalnessTexture.Location = 135;
    u_MetalnessTexture.SamplerID = 2;
    u_RoughnessTexture.Location = 136;
    u_RoughnessTexture.SamplerID = 3;
    u_AmbientTexture.Location = 137;
    u_AmbientTexture.SamplerID = 4;
    u_EmissiveTexture.Location = 138;
    u_EmissiveTexture.SamplerID = 5;
    u_AlbedoColor.Location = 139;
    u_Metalness.Location = 140;
    u_Roughness.Location = 141;
    u_TextureScale.Location = 142;
    u_EmissiveColor.Location = 143;
    r_AlbedoTexToggle.Location = 144;
    r_NormalTexToggle.Location = 145;
    r_MetalnessTexToggle.Location = 146;
    r_RoughnessTexToggle.Location = 147;
    r_AmbientTexToggle.Location = 148;
    r_EmissiveTexToggle.Location = 149;
    r_gammaCorrect.Location = 150;
}
void shader_Screen::InitShaderLocs() {
    outputs.num_outputs = 0;

    u_albedo.Location = 1;
    u_albedo.SamplerID = 0;
    u_normal.Location = 2;
    u_normal.SamplerID = 1;
    u_amr.Location = 3;
    u_amr.SamplerID = 2;
    u_depth.Location = 4;
    u_depth.SamplerID = 3;
    u_diffuse.Location = 5;
    u_diffuse.SamplerID = 4;
    u_specular.Location = 6;
    u_specular.SamplerID = 5;
    u_emissive.Location = 7;
    u_emissive.SamplerID = 6;
    u_ssao.Location = 8;
    u_ssao.SamplerID = 7;
    r_outputSwitch.Location = 9;
    r_toneMap.Location = 10;
    r_gammaCorrect.Location = 11;
}
void shader_simple::InitShaderLocs() {
    outputs.num_outputs = 1;
    outputs.FragColor = 0;

    r_VP.Location = 1;
    r_Transform.Location = 2;
    u_texture.Location = 3;
    u_texture.SamplerID = 0;
    u_color.Location = 4;
}
void shader_Simple_static::InitShaderLocs() {
    outputs.num_outputs = 1;
    outputs.FragColor = 0;

    r_VP.Location = 1;
    r_Transform.Location = 2;
    u_texture.Location = 3;
    u_texture.SamplerID = 0;
    u_color.Location = 4;
}
void shader_simple_triplanar::InitShaderLocs() {
    outputs.num_outputs = 1;
    outputs.FragColor = 0;

    r_VP.Location = 1;
    r_Transform.Location = 2;
    u_texture.Location = 3;
    u_texture.SamplerID = 0;
    u_color.Location = 4;
}
void shader_Skybox::InitShaderLocs() {
    outputs.num_outputs = 0;

    r_View.Location = 1;
    r_Projection.Location = 2;
    u_skybox.Location = 3;
    u_skybox.SamplerID = 0;
    r_toneMap.Location = 4;
    r_gammaCorrect.Location = 5;
}
void shader_Sobel::InitShaderLocs() {
    outputs.num_outputs = 0;

    r_texture.Location = 1;
    r_texture.SamplerID = 0;
}
void shader_Sprite::InitShaderLocs() {
    outputs.num_outputs = 0;

    r_transform.Location = 1;
    r_transformUV.Location = 2;
    r_orthoProjection.Location = 3;
    r_spriteTex.Location = 4;
    r_spriteTex.SamplerID = 0;
    r_textColor.Location = 5;
}
void shader_SSAO::InitShaderLocs() {
    outputs.num_outputs = 1;
    outputs.out_SSAO = 0;

    u_amr.Location = 1;
    u_amr.SamplerID = 0;
}
void shader_wireframe::InitShaderLocs() {
    outputs.num_outputs = 1;
    outputs.FragColor = 0;

    r_VP.Location = 1;
    r_Transform.Location = 2;
    u_texture.Location = 3;
    u_texture.SamplerID = 0;
    u_color.Location = 4;
}
// End of codegen
